# Generated by Django 4.1.2 on 2022-11-17 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='helpdesk/covers/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='comment',
            name='status_modify',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Execução', 'Execução'), ('Fechado', 'Fechado')], default='Aberto', max_length=12),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Tarefa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.tarefa', verbose_name='Tarefa'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpdesk.category', verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='helpdesk/covers/%Y/%m/%d/', verbose_name='Anexo'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='prioridade',
            field=models.CharField(max_length=20, verbose_name='Prioridade'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Execução', 'Execução'), ('Fechado', 'Fechado')], default='Aberto', max_length=12),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='title',
            field=models.CharField(max_length=65, verbose_name='Título'),
        ),
    ]
