# Generated by Django 4.1.2 on 2022-11-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='helpdesk/covers/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Execução', 'Execução'), ('Fechado', 'Fechado')], default='Aberto', max_length=12),
        ),
    ]
