# Generated by Django 4.1.2 on 2022-11-18 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_comment_cover_comment_status_modify_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='helpdesk/covers/%Y/%m/%d/', verbose_name='Anexo'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(default='Complemento', max_length=255),
        ),
        migrations.AlterField(
            model_name='comment',
            name='status_modify',
            field=models.CharField(blank=True, choices=[('Aberto', 'Aberto'), ('Execução', 'Execução'), ('Finalizado', 'Finalizado')], default='Aberto', max_length=12, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(blank=True, choices=[('Aberto', 'Aberto'), ('Execução', 'Execução'), ('Fechado', 'Fechado')], default='Aberto', max_length=12, null=True),
        ),
    ]
