# Generated by Django 4.1.2 on 2022-11-01 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Comments',
        ),
    ]
