# Generated by Django 4.1.2 on 2022-11-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_alter_comment_cover_alter_comment_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='global_msg',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
