# Generated by Django 4.1.2 on 2022-11-25 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0005_remove_comment_global_msg_tarefa_global_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasktipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(max_length=35, verbose_name='Tipo de Tarefa')),
            ],
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='global_msg',
            field=models.BooleanField(default=False, verbose_name='Mensagem Global'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(blank=True, choices=[('Aberto', 'Aberto'), ('Execução', 'Execução'), ('Finalizado', 'Finalizado')], default='Aberto', max_length=12, null=True),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('Comment', 'Comment'), ('New Task', 'New Task'), ('Status', 'Status')], max_length=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visualization', models.BooleanField(default=False)),
                ('Tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helpdesk.tarefa', verbose_name='Tarefa')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
        ),
        migrations.AddField(
            model_name='tarefa',
            name='tipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpdesk.tasktipe', verbose_name='Tipo de Tarefa'),
        ),
    ]
