# Generated by Django 4.1.2 on 2022-11-24 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0005_remove_comment_global_msg_tarefa_global_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='global_msg',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(blank=True, choices=[('Aberto', 'Aberto'), ('Execução', 'Execução'), ('Finalizado', 'Finalizado')], default='Aberto', max_length=12, null=True),
        ),
    ]
