# Generated by Django 4.1.2 on 2022-11-01 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0005_comment_delete_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='tarefa',
            new_name='Tarefa',
        ),
    ]
