# Generated by Django 4.1.2 on 2022-11-26 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_alter_tarefa_global_msg_alter_tarefa_status'),
        ('helpdesk', '0007_location_tarefa_local'),
    ]

    operations = [
    ]
