# Generated by Django 4.1.2 on 2022-11-07 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0008_alter_tarefa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='Category',
            field=models.ForeignKey(blank=True, default='Geral', null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpdesk.category'),
        ),
    ]
