# Generated by Django 4.1.2 on 2022-11-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0008_merge_20221126_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='global_msg',
            field=models.BooleanField(default=False, verbose_name='Mensagem Global'),
        ),
    ]
