# Generated by Django 4.1.2 on 2022-11-07 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0009_alter_tarefa_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpdesk.category'),
        ),
    ]
