# Generated by Django 4.1.2 on 2022-12-01 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0009_alter_tarefa_global_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='Category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpdesk.category', verbose_name='Setor Responsável'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(blank=True, choices=[('Aberto', 'Aberto'), ('Execução', 'Execução'), ('Finalizado', 'Finalizado'), ('Global', 'Global')], default='Aberto', max_length=12, null=True),
        ),
    ]
