# Generated by Django 4.1.2 on 2022-12-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0010_alter_tarefa_category_alter_tarefa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(blank=True, choices=[('Aberto', 'Aberto'), ('Execução', 'Execução'), ('Finalizado', 'Finalizado')], default='Aberto', max_length=12, null=True),
        ),
    ]
