# Generated by Django 4.1.2 on 2022-12-07 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_alter_tarefa_cover_alter_tarefa_status'),
        ('helpdesk', '0011_alter_tarefa_status'),
    ]

    operations = [
    ]
