# Generated by Django 4.1.2 on 2022-12-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0012_merge_20221207_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='helpdesk/covers/%Y/%m/%d/', verbose_name='Anexo'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(blank=True, choices=[('Aberto', 'Aberto'), ('Execução', 'Execução'), ('Finalizado', 'Finalizado')], default='Aberto', max_length=12, null=True),
        ),
    ]
