# Generated by Django 4.1.2 on 2022-12-15 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0013_alter_tarefa_cover_alter_tarefa_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='title',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='setor_author',
            field=models.CharField(blank=True, max_length=65, null=True, verbose_name='Setor do Autor'),
        ),
    ]
