# Generated by Django 4.1.2 on 2022-12-01 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0010_alter_tarefa_category_alter_tarefa_status'),
        ('authors', '0003_remove_profile_cover_profile_cover_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.GenericIPAddressField(verbose_name='IP')),
            ],
        ),
        migrations.CreateModel(
            name='Usuariofc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9, verbose_name='Usuario Fórmula Certa')),
            ],
        ),
        migrations.CreateModel(
            name='Maquinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome da Maquina')),
                ('config', models.CharField(max_length=100, verbose_name='Config da maquina')),
                ('anydesk', models.CharField(max_length=11, verbose_name='Anydesk')),
                ('usuario2', models.CharField(max_length=30, verbose_name='Usuario Temporario')),
                ('ramal', models.CharField(max_length=4, null=True, verbose_name='Ramal')),
                ('email', models.CharField(max_length=65, verbose_name='E-Mail')),
                ('skype', models.CharField(max_length=65, verbose_name='Skype ID')),
                ('windows', models.CharField(max_length=6, verbose_name='Versão do Windows')),
                ('celular', models.CharField(max_length=11, null=True, verbose_name='Numero de Celular')),
                ('gmail', models.CharField(max_length=65, null=True, verbose_name='Conta Google')),
                ('e7', models.BooleanField(default=False, verbose_name='E7 Antivirus instalado?')),
                ('office', models.BooleanField(default=False, verbose_name='Office instalado?')),
                ('data_at', models.DateTimeField(auto_now_add=True)),
                ('data_up_at', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpdesk.category', verbose_name='Setor')),
                ('ip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authors.ip', verbose_name='IP Address')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('usuariofc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authors.usuariofc', verbose_name='Usuario Conexão Fórmula Certa')),
            ],
        ),
    ]
