# Generated by Django 4.1.2 on 2022-12-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0004_ip_usuariofc_maquinas'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinas',
            name='ativo',
            field=models.BooleanField(default=False, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='maquinas',
            name='usuario2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Usuario Temporario'),
        ),
    ]
