# Generated by Django 4.1.2 on 2022-12-02 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_maquinas_ativo_alter_maquinas_usuario2'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.maquinas', verbose_name='Maquina'),
        ),
    ]
