# Generated by Django 4.1.2 on 2022-12-16 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0007_maquinas_mac_alter_maquinas_ativo_alter_maquinas_e7_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maquinas',
            name='ativo',
            field=models.BooleanField(default=False, verbose_name='Máquina Ativa'),
        ),
        migrations.AlterField(
            model_name='maquinas',
            name='config',
            field=models.CharField(max_length=100, verbose_name='Configurações da máquina'),
        ),
        migrations.AlterField(
            model_name='maquinas',
            name='mac',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='MAC'),
        ),
        migrations.AlterField(
            model_name='maquinas',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Nome da Máquina'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='maquina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.maquinas', verbose_name='Máquina'),
        ),
    ]
