# Generated by Django 4.1.2 on 2022-12-16 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0014_remove_tarefa_title_tarefa_setor_author'),
        ('authors', '0008_alter_maquinas_ativo_alter_maquinas_config_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impressora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Impressora')),
                ('mac', models.CharField(max_length=17, verbose_name='MAC')),
                ('Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpdesk.category', verbose_name='Setor')),
                ('ip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authors.ip', verbose_name='IP Address')),
            ],
        ),
        migrations.AddField(
            model_name='maquinas',
            name='impressora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authors.impressora', verbose_name='Impressora padrão'),
        ),
    ]
